### ISSUE TITLE
lib/ppx_pattern_bind is essentially empty (v0.13 on ocaml 4.09.0)

### ISSUE THREAD

**Issue by phstrauss** [janestreet/ppx_pattern_bind#1]
my ppx_pattern_bind v0.13 opam install of the day is empty, it contains an empty META file, a very tiny dune file and an opam file, no .ml .mli .cm* files.

**Comment by phstrauss** [comment]
in the git repos, ppx_pattern_bind.mli is empty, zero bytes.

**Comment by xclerc** [comment]
The fact that `ppx_pattern_bind.mli` is, I think, expected.
However, it is true that the `dune` file is wrong, and basically
makes the package useless. We will publish a point release
to fix that.

**Comment by xclerc** [comment]
(Fixed by https://github.com/ocaml/opam-repository/pull/15358.)
